In [2]:
import numpy as np

## Create numpy arrays
Arrays can be created in different ways, which we will show in the following code examples.

In [ ]:
# One dimensional array
one_dim_array=np.array([7,2,9,10])
print (one_dim_array)
print (one_dim_array.shape)

[ 7  2  9 10]
(4,)


In [3]:
# Two dimensional array
two_dim_array=np.array([(5.2,3.0,4.5),(9.1,0.1,0.3)])
print ('Array:')
print (two_dim_array)
print ('Shape: ',two_dim_array.shape)
print ('Item at [1,0] = ',two_dim_array[1][0])

Array:
[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
Shape:  (2, 3)
Item at [1,0] =  9.1


In [35]:
# Three dimensional array

three_dim_array= np.zeros((3,4,5))
three_dim_array[0][2][2]=123
three_dim_array[1][3][4]=145
print ('Array:')
print (three_dim_array)
print ('Shape: ',three_dim_array.shape)

print ('Item at [0,2,2] = ',three_dim_array[0][2][2])

Array:
[[[  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]
  [  0.   0. 123.   0.   0.]
  [  0.   0.   0.   0.   0.]]

 [[  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0. 145.]]

 [[  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.]]]
Shape:  (3, 4, 5)
Item at [0,0,2] =  123.0
