# Create arrays with initial placeholders
Shows how to create arrays using initial values or random values

In [2]:
import numpy as np

## Fill with specific values
### a. Fill with zeros
*Syntax:*

>```python
np.zeros(shape,dtype,order)
```

*Explanation:*
>Returns a new array of specified size, filled with zeros.

*Parameters:* 
>- shape size of array as int or list, eg. [3,2,3] for a 3 dimensional array with dimension size of 3,2 and 3
- dtype type of array items
- order 'C' for C-style row-major array, 'F' for FORTRAN style column-major array

*Example:*
>```python
np.zeros(2,4,3)
```

In [3]:
print (np.zeros([2,3,4],dtype=np.int16,order='C'))

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


### b. Fill with ones

*Syntax:*

>```python
np.ones(shape,dtype,order) 
```

*Explanation:* 
>Returns a new array of specified size, filled with zeros.

*Parameters:* 
>- **shape:** size of array as int or list, eg. [3,2,3] for a 3 dimensional array with dimension size of 3,2 and 3
- **dtype:** type of array items
- **order:** 'C' for C-style row-major array, 'F' for FORTRAN style column-major array

*Example:*
>```python
np.ones(2,4,3)
```

In [30]:
a=np.ones([2,4,3])
print(a)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


The first dimension shows up in the two blocks, the second is the number of rows in each block and the third is the number of columns.