# Create arrays with initial placeholders
Shows how to create arrays using initial values or random values

In [1]:
import numpy as np

### Fill with zeros
Syntax: np.zeros(shape,dtype,order)
Explanation: Returns a new array of specified size, filled with zeros.
Parameters: 
- shape size of array as int or list, eg. [3,2,3] for a 3 dimensional array with dimension size of 3,2 and 3
- dtype type of array items
- order 'C' for C-style row-major array, 'F' for FORTRAN style column-major array

In [13]:
print (np.zeros([2,3,4],dtype=np.int16,order='C'))

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
