# Array Inspection
NdArrays can be inspected in various ways.

- shape
- size
- ndim
- dtype

In [2]:
import numpy as np

### Shape

*Syntax:*

>array.shape

*Explanation:*
>This array attribute returns a tuple consisting of array dimensions. 
>It can also be used to resize the array. However changing the size is possible only if the **total number of array elements remains the same**.

In [8]:
# Get the shape of an array
a=np.zeros([2,4,3])
print ("Array:\n",a)

print("Shape:",a.shape)

Array:
 [[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
Shape: (2, 4, 3)


In [11]:
# Change the shape
a.shape=(2,3,4)
print("Reshaped array:\n",a)

Reshaped array:
 [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [30]:
# Another example creating a flat (one dimensional) array and then reshaping
b=np.arange(0,24)
print (b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1


In [23]:
b.shape=(2,3,4)
print("Reshaped array:",b)

Reshaped array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


---
### Size

*Syntax:*

>array.size

*Explanation:*
>The attribute *size* contains the number of items an array contains.

In [29]:
print ("Size:",b.size)

Size: 24


---
### Ndim

*Syntax:*

>array.ndim

*Explanation:*
>The attribute *ndim* contains dimensions of the array.

In [28]:
print ("ndim:",b.ndim)

ndim: 3
